services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ConstraintsAddAction: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ConstraintsRemoveAction: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ToggleClassAction: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ToggleElementAction: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\SwitchOutputWorkflowAction: ~

    FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\SuccessMessageAction: ~