sudo: true
language: php
addons:
    chrome: stable
    mariadb: '10.2'
    apt:
        packages:
            - html2text
services:
    - mysql
env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - DACHCOM_BUNDLE_TEST=1
        - PIMCORE_TEST_URL=http://localhost
        - CHROME_DRIVER_VERSION=2.41
        - SELENIUM_VERSION=3.6.0
        - WEBDRIVER_HOST=localhost
        - WEBDRIVER_URL="http://localhost:8080/"
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/dachcom_bundle_test"
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - DACHCOM_TEST_SECTION=codeception
        - SYMFONY_VERSION=^4.0
        - PIMCORE_PHP_ERROR_REPORTING=32767 # E_ALL
matrix:
    include:
        -   name: "PHPStan Static Analysis (Pimcore 6.6.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
                - DACHCOM_TEST_SECTION=phpstan
        -   name: "PHP ECS (Pimcore 6.6.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
                - DACHCOM_TEST_SECTION=ecs
        -   name: "Codeception Tests (Pimcore 6.0.x, Symfony ^4.3, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - SYMFONY_VERSION="~4.3.0"
                - PIMCORE_SKELETON_BRANCH="tags/v2.0.0"
        -   name: "Codeception Tests (Pimcore 6.1.x, Symfony ^4.3, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - SYMFONY_VERSION="~4.3.0"
                - PIMCORE_SKELETON_BRANCH="tags/v2.1.0"
        -   name: "Codeception Tests (Pimcore 6.2.x, Symfony ^4.3, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - SYMFONY_VERSION="~4.3.0"
                - PIMCORE_SKELETON_BRANCH="tags/v2.2.0"
        -   name: "Codeception Tests (Pimcore 6.3.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_PHP_ERROR_REPORTING=30711 # E_ALL & ~E_NOTICE & ~E_STRICT
                - PIMCORE_SKELETON_BRANCH="tags/v2.3.0"
        -   name: "Codeception Tests (Pimcore 6.4.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.4.0"
        -   name: "Codeception Tests (Pimcore 6.5.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.5.0"
        -   name: "Codeception Tests (Pimcore 6.6.x, Symfony ^4.0, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
        -   name: "Codeception Tests (Pimcore 6.6.x, Symfony ^3.4, PHP 7.3)"
            sudo: required
            php: 7.3
            env:
                - SYMFONY_VERSION=^3.4
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
        -   name: "Codeception Tests (Pimcore 6.6.x, Symfony ^4.0, PHP 7.4)"
            sudo: required
            php: 7.4
            env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
    allow_failures:
        -   env:
                - PIMCORE_SKELETON_BRANCH="tags/v2.6.0"
                - DACHCOM_TEST_SECTION=ecs
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

install:
    - tests/_etc/travis/install

after_failure:
    - cd $TRAVIS_BUILD_DIR
    - cat ./lib/FormBuilder/tests/_output/*.html

before_script:
    - phpenv config-rm xdebug.ini

script:
    - '$HOME/chromedriver --url-base=/wd/hub &'
    - 'php ${TRAVIS_BUILD_DIR}/bin/console server:start 127.0.0.1:8080 -d web'
    - 'php ${TRAVIS_BUILD_DIR}/bin/console server:status'
    - _etc/travis/script

notifications:
    email:
        - shagspiel@dachcom.ch