form_builder:
    types:
        text:
            class: Symfony\Component\Form\Extension\Core\Type\TextType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.text_type'
                icon_class: 'form_builder_icon_text'
        hidden:
            class: Symfony\Component\Form\Extension\Core\Type\HiddenType
            backend:
                form_type_group: hidden_fields
                label: 'form_builder_type.hidden_type'
                icon_class: 'form_builder_icon_hidden'
        textarea:
            class: Symfony\Component\Form\Extension\Core\Type\TextareaType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.textarea_type'
                icon_class: 'form_builder_icon_textarea'
        integer:
            class: Symfony\Component\Form\Extension\Core\Type\IntegerType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.integer_type'
                icon_class: 'form_builder_icon_integer'
        checkbox:
            class: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.checkbox_type'
                icon_class: 'form_builder_icon_checkbox'
        submit:
            class: Symfony\Component\Form\Extension\Core\Type\SubmitType
            backend:
                form_type_group: buttons
                label: 'form_builder_type.submit_type'
                icon_class: 'form_builder_icon_button'
                constraints: false
                fields:
                    options.required: ~
                    optional.email_label: ~
                    options.data: ~
        dynamic_multi_file:
            class: FormBuilderBundle\Form\Type\DynamicMultiFileType
            backend:
                form_type_group: other_fields
                label: 'form_builder_type.dynamic_multi_file'
                icon_class: 'form_builder_icon_file'
                fields:
                    options.allowed_extensions:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.allowed_extensions'
                        config: ~
                    options.allowed_extensions_label:
                        display_group_id: attributes
                        type: label
                        label: 'form_builder_type_field.allowed_extensions_desc'
                    options.max_file_size:
                        display_group_id: attributes
                        type: textfield
                        label: 'form_builder_type_field.max_file_size'
                        config: ~
                    options.max_file_size_label:
                        display_group_id: attributes
                        type: label
                        label: 'form_builder_type_field.max_file_size_desc'
        choice:
            class: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            backend:
                form_type_group: choice_fields
                label: 'form_builder_type.choice_type'
                icon_class: 'form_builder_icon_multi_select'
                fields:
                    options.expanded:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.expanded'
                        config: ~
                    options.multiple:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.multiple'
                        config: ~
                    options.choices:
                        display_group_id: attributes
                        type: key_value_repeater
                        label: 'form_builder_type_field.choices'
                        options_transformer: 'form_builder.options_transformer.choices'
                        config: ~
        hidden:
            class: Symfony\Component\Form\Extension\Core\Type\HiddenType
            backend:
                form_type_group: hidden_fields
                label: 'form_builder_type.hidden_type'
                icon_class: 'form_builder_icon_hidden'