form_builder:
    types:
        dynamic_choice:
            class: FormBuilderBundle\Form\Type\DynamicChoiceType
            output_transformer: choice_transformer
            backend:
                form_type_group: choice_fields
                label: 'form_builder_type.dynamic_choice_type'
                icon_class: 'form_builder_icon_dynamic_multi_select'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                output_workflow:
                    object:
                        allowed_class_types:
                            - input
                            - select
                            - multiselect
                fields:
                    options.value: ~
                    options.data:
                        display_group_id: base
                        type: tagfield
                        label: 'form_builder_type_field_base.preselected'
                        config: ~
                    options.preferred_choices:
                        display_group_id: base
                        type: tagfield
                        label: 'form_builder_type_field_base.preferred_choices'
                        config: ~
                    options.expanded:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.expanded'
                        config: ~
                    options.multiple:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.multiple'
                        config: ~
                    options.placeholder:
                        display_group_id: attributes
                        type: textfield
                        label: 'form_builder_type_field.placeholder'
                        options_transformer: FormBuilderBundle\Transformer\DefaultValueTransformer
                        config:
                            default_value: false
                    options.service:
                        display_group_id: attributes
                        type: select
                        label: 'form_builder_type_field.service_name'
                        config:
                            store_url: '/admin/formbuilder/settings/get-dynamic-choice-builder'