form_builder:
    types:
        date_time:
            class: Symfony\Component\Form\Extension\Core\Type\DateTimeType
            output_transformer: date_transformer
            input_transformer: date_transformer
            backend:
                form_type_group: date_time_fields
                label: 'form_builder_type.date_time_type'
                icon_class: 'form_builder_icon_date_time'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                output_workflow:
                    object:
                        allowed_class_types:
                            - datetime
                fields:
                    options.data: ~
                    options.value: ~
                    options.date_widget:
                        display_group_id: attributes
                        type: select
                        label: 'form_builder_type_field.date_widget'
                        config:
                            options:
                                - ['Choice', 'choice']
                                - ['Text', 'text']
                                - ['Single Text', 'single_text']
                    options.time_widget:
                        display_group_id: attributes
                        type: select
                        label: 'form_builder_type_field.time_widget'
                        config:
                            options:
                                - ['Choice', 'choice']
                                - ['Text', 'text']
                                - ['Single Text', 'single_text']
                    options.seconds:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_seconds'
                        config: ~
                    options.minutes:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_minutes'
                        config: ~
                    options.hours:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_hours'
                        config: ~
                    options.days:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_days'
                        config: ~
                    options.months:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_months'
                        config: ~
                    options.years:
                        display_group_id: attributes
                        type: tagfield
                        label: 'form_builder_type_field.date_years'
                        config: ~
                    options.with_minutes:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.date_with_minutes'
                    options.with_seconds:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.date_with_seconds'
                    options.html5:
                        display_group_id: attributes
                        type: checkbox
                        label: 'form_builder_type_field.date_html5'
                        config:
                            checked: true
