form_builder:
    types:
        integer:
            class: Symfony\Component\Form\Extension\Core\Type\IntegerType
            backend:
                form_type_group: text_fields
                label: 'form_builder_type.integer_type'
                icon_class: 'form_builder_icon_integer'
                constraints:
                    disabled:
                        - 'dynamic_multi_file_not_blank'
                fields:
                    options.value: ~