imports:
    - { resource: form_types.yml }

services:

    # tool installer
    form_builder.tool.installer:
        class: FormBuilderBundle\Tool\Install
        arguments: ['@logger']
        tags:
            - { name: monolog.logger }

    # configuration
    form_builder.configuration:
        class: FormBuilderBundle\Configuration\Configuration

    # session: configurator
    form_builder.session.configurator:
        class: FormBuilderBundle\Session\SessionConfigurator
        tags:
            - { name: pimcore.session.configurator }

    # area brick
    form_builder.area.brick.form:
        class: FormBuilderBundle\Document\Areabrick\Form\Form
        arguments:
            - '@session'
            - '@form_builder.manager.form'
            - '@form_builder.manager.preset'
            - '@form_builder.form_builder'
            - '@form_builder.manager.template'
            - '@pimcore.translator'
        tags:
            - { name: pimcore.area.brick, id: formbuilder_form }

    # factory: form
    form_builder.factory.form:
        class: FormBuilderBundle\Factory\FormFactory
        arguments:
            - '@pimcore.translator'

    # manager: form
    form_builder.manager.form:
        class: FormBuilderBundle\Manager\FormManager
        arguments:
            - '@form_builder.factory.form'

    # manager: preset
    form_builder.manager.preset:
        class: FormBuilderBundle\Manager\PresetManager
        arguments:
            - '@form_builder.configuration'

    # manager: template (form themes, type templates)
    form_builder.manager.template:
        class: FormBuilderBundle\Manager\TemplateManager
        arguments:
            - '@form_builder.configuration'

    # registry: form_types
    form_builder.registry.form_type:
        class: FormBuilderBundle\Registry\FormTypeRegistry
        arguments:
            - FormBuilderBundle\Form\Type\TypeInterface

    #parser: mail
    form_builder.parser.mail:
        shared: false
        class: FormBuilderBundle\Parser\MailParser
        arguments:
            - '@templating'

    # form builder
    form_builder.form_builder:
        class: FormBuilderBundle\Form\Builder
        arguments:
            - '@request_stack'
            - '@form_builder.manager.form'
            - '@form.factory'
            - '@form_builder.registry.form_type'

    # core event: request
    form_builder.core_listener.request:
        class: FormBuilderBundle\EventListener\Core\RequestListener
        arguments:
            - '@form_builder.form_builder'
            - '@event_dispatcher'
            - '@session'
        tags:
            - { name: kernel.event_subscriber }

    # event: mail
    form_builder.event_listener.mail:
        class: FormBuilderBundle\EventListener\MailListener
        arguments:
            - '@session'
            - '@form_builder.parser.mail'
        tags:
            - { name: kernel.event_subscriber }

    # backend form builder
    form_builder.backend.form_builder:
        class: FormBuilderBundle\Backend\Form\Builder
        arguments:
            - '@form_builder.configuration'
            - '@form_builder.registry.form_type'
            - '@form_builder.manager.template'
            - '@pimcore.translator'