parameters:
    form_builder_html_tag_elements:
        - ['label','label']

form_builder:
    area:
        presets: ~
    form:
        templates:
            form_div_layout:
                value: 'form_div_layout.html.twig'
                label: 'form_builder_form_template.form_div_layout'
                default: false
            bootstrap_3_layout:
                value: 'bootstrap_3_layout.html.twig'
                label: 'form_builder_form_template.bootstrap_3_layout'
                default: true
            bootstrap_3_horizontal_layout:
                value: 'bootstrap_3_horizontal_layout.html.twig'
                label: 'form_builder_form_template.bootstrap_3_horizontal_layout'
                default: false
        field:
            templates:
                default:
                    value: 'default'
                    label: 'form_builder_type_template.default'
                    default: true
    admin:
        active_elements:
            fields: []

    conditional_logic:
        action:
            toggleElement:
                name: 'form_builder.cl.action.toggle_element'
                icon: 'form_builder_cl_toggle_element'
            constraintsAdd:
                class: 'FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ConstraintsAddAction'
                name: 'form_builder.cl.action.constraints_add'
                icon: 'form_builder_cl_constraints_add'
            constraintsRemove:
                class: 'FormBuilderBundle\Validation\ConditionalLogic\Rule\Action\ConstraintsRemoveAction'
                name: 'form_builder.cl.action.constraints_remove'
                icon: 'form_builder_cl_constraints_remove'
            changeValue:
                name: 'form_builder.cl.action.change_value'
                icon: 'form_builder_cl_change_value'
            triggerEvent:
                name: 'form_builder.cl.action.trigger_event'
                icon: 'form_builder_cl_trigger_event'
            toggleClass:
                name: 'form_builder.cl.action.toggle_class'
                icon: 'form_builder_cl_toggle_class'
        condition:
            elementValue:
                class: 'FormBuilderBundle\Validation\ConditionalLogic\Rule\Condition\ElementValueCondition'
                name: 'form_builder.cl.condition.element_value'
                icon: 'form_builder_cl_element_value'
imports:
    - { resource: '../backend/base_config.yml' }
    - { resource: '../types/types.yml' }
    - { resource: '../extension/extension.yml' }