form_builder.controller.admin.get_tree:
    path: /admin/formbuilder/settings/get-tree
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::getTreeAction }
form_builder.controller.admin.get_settings:
    path: /admin/formbuilder/settings/get-settings
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::getSettingsAction }
form_builder.controller.admin.get_dynamic_choice_builder:
    path: /admin/formbuilder/settings/get-dynamic-choice-builder
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::getDynamicChoiceBuilderAction }

form_builder.controller.admin.get_form:
    path: /admin/formbuilder/settings/get-form
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::getFormAction }
form_builder.controller.admin.add_form:
    path: /admin/formbuilder/settings/add-form
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::addFormAction }
form_builder.controller.admin.save_form:
    path: /admin/formbuilder/settings/save-form
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::saveFormAction }
form_builder.controller.admin.delete_form:
    path: /admin/formbuilder/settings/delete-form
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::deleteFormAction }

form_builder.controller.admin.load_form_mail_editor_data:
    path: /admin/formbuilder/mail-editor/load
    defaults: { _controller: FormBuilderBundle\Controller\Admin\MailEditorController::getMailEditorDataAction }
form_builder.controller.admin.save_form_mail_editor_data:
    path: /admin/formbuilder/mail-editor/save
    defaults: { _controller: FormBuilderBundle\Controller\Admin\MailEditorController::saveFormMailEditorDataAction }
form_builder.controller.admin.get_available_mail_types:
    path: /admin/formbuilder/mail-editor/get-available-mail-types
    defaults: { _controller: FormBuilderBundle\Controller\Admin\MailEditorController::getMailEditorAvailableMailTypesAction }
form_builder.controller.admin.delete_mail_type:
    path: /admin/formbuilder/mail-editor/delete-mail-type
    defaults: { _controller: FormBuilderBundle\Controller\Admin\MailEditorController::deleteMailEditorMailTypeAction }

form_builder.controller.admin.export_form:
    path: /admin/formbuilder/settings/export-form/{id}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::exportFormAction }
form_builder.controller.admin.import_form:
    path: /admin/formbuilder/settings/import-form/{id}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::importFormAction }

form_builder.controller.admin.csv_export.export:
    path: /admin/formbuilder/export/mail-csv-export/{id}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\ExportController::exportFormEmailsAction }

form_builder.controller.admin.check_path:
    path: /admin/formbuilder/settings/check-path
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::checkPathAction }
form_builder.controller.admin.get_group_templates:
    path: /admin/formbuilder/settings/get-group-templates
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::getGroupTemplatesAction }

form_builder.controller.admin.get_form_dependencies:
    path: /admin/formbuilder/settings/get-form-dependencies
    defaults: { _controller: FormBuilderBundle\Controller\Admin\SettingsController::findFormDependenciesAction }

form_builder.controller.ajax.url_structure:
    path: /{_locale}/form-control/get-url-structure
    defaults: { _controller: FormBuilderBundle\Controller\AjaxController::getAjaxUrlStructureAction }
    methods: [POST]
form_builder.controller.ajax.parse_form:
    path: /{_locale}/form-control/parse
    defaults: { _controller: FormBuilderBundle\Controller\AjaxController::parseAction }
    methods: [POST]
form_builder.controller.ajax.file_chunk_done:
    path: /{_locale}/form-control/file-chunk
    defaults: { _controller: FormBuilderBundle\Controller\AjaxController::fileChunkDoneAction }
    methods: [POST]
form_builder.controller.ajax.file_add:
    path: /{_locale}/form-control/file-add
    defaults: { _controller: FormBuilderBundle\Controller\AjaxController::fileAddAction }
    methods: [POST]
form_builder.controller.ajax.file_delete:
    path: /{_locale}/form-control/file-delete/{uuid}
    defaults: { _controller: FormBuilderBundle\Controller\AjaxController::fileDeleteAction, uuid: '' }
    methods: [POST, DELETE]

# Output Workflows
form_builder.controller.admin.output_workflow.get_output_workflow_tree:
    path: /admin/formbuilder/output-workflow/get-output-workflow-tree/{formId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::getOutputWorkflowTreeAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.get_output_workflow_list:
    path: /admin/formbuilder/output-workflow/get-output-workflow-list/{formId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::getOutputWorkflowListAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.add_output_workflow:
    path: /admin/formbuilder/output-workflow/add-output-workflow/{formId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::addOutputWorkflowAction }
    methods: [POST]

form_builder.controller.admin.output_workflow.delete_output_workflow:
    path: /admin/formbuilder/output-workflow/delete-output-workflow/{outputWorkflowId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::deleteOutputWorkflowAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.save_output_workflow:
    path: /admin/formbuilder/output-workflow/save-output-workflow/{outputWorkflowId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::saveOutputWorkflowAction }
    methods: [POST]

form_builder.controller.admin.output_workflow.get_output_workflow_data:
    path: /admin/formbuilder/output-workflow/get-output-workflow-data/{outputWorkflowId}
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowController::getOutputWorkflowDataAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.object.get_object_classes:
    path: /admin/formbuilder/output-workflow/object/get-object-classes
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowObjectController::getObjectClassesAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.object.get_object_class_fields:
    path: /admin/formbuilder/output-workflow/object/get-object-class-fields
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowObjectController::getObjectClassesFieldsAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.object.get_field_collection_types:
    path: /admin/formbuilder/output-workflow/object/get-field-collection-types
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowObjectController::getFieldCollectionTypesForDataTypeAction }
    methods: [GET]

form_builder.controller.admin.output_workflow.object.get_form_data:
    path: /admin/formbuilder/output-workflow/object/get-form-data
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowObjectController::getFormDataAction }
    methods: [POST]

form_builder.controller.admin.output_workflow.object.get_dynamic_object_resolver:
    path: /admin/formbuilder/output-workflow/object/get-dynamic-object-resolver
    defaults: { _controller: FormBuilderBundle\Controller\Admin\OutputWorkflowObjectController::getDynamicObjectResolverAction }
    methods: [GET]