services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # event subscriber: builder
    FormBuilderBundle\EventSubscriber\FormBuilderSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # core event: request
    FormBuilderBundle\EventListener\Core\RequestListener:
        tags:
            - { name: kernel.event_subscriber }

    # core event: clean up unused tmp files
    FormBuilderBundle\EventListener\Core\CleanUpListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: mail
    FormBuilderBundle\EventListener\MailListener:
        tags:
            - { name: kernel.event_subscriber }