services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Validation\ConditionalLogic\Factory\DataFactory:
        arguments: [!tagged form_builder.module.data]

    # Module
    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\Constraints:
        tags:
            - { name: 'form_builder.dispatcher', type: 'constraints' }

    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\FormTypeClasses:
        tags:
            - { name: 'form_builder.dispatcher', type: 'form_type_classes' }

    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\MailBehaviour:
        tags:
            - { name: 'form_builder.dispatcher', type: 'mail_behaviour' }

    # Data
    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\Data\ConstraintsData:
        shared: false
        tags:
            - { name: 'form_builder.module.data' }

    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\Data\FormTypeClassesData:
        shared: false
        tags:
            - { name: 'form_builder.module.data' }

    FormBuilderBundle\Validation\ConditionalLogic\Dispatcher\Module\Data\MailBehaviourData:
        shared: false
        tags:
            - { name: 'form_builder.module.data' }