services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\OutputWorkflow\Channel\Email\EmailOutputChannelWorker: ~
    FormBuilderBundle\OutputWorkflow\Channel\Email\EmailOutputChannel:
        tags:
            - { name: form_builder.output_workflow.channel, type: email }

    FormBuilderBundle\OutputWorkflow\Channel\Email\Parser\MailParser:
        shared: false

    FormBuilderBundle\OutputWorkflow\Channel\Object\ObjectOutputChannel:
        tags:
            - { name: form_builder.output_workflow.channel, type: object }

    FormBuilderBundle\OutputWorkflow\Channel\Api\ApiOutputChannelWorker: ~
    FormBuilderBundle\OutputWorkflow\Channel\Api\ApiOutputChannel:
        tags:
            - { name: form_builder.output_workflow.channel, type: api }