services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FormBuilderBundle\OutputWorkflow\SuccessManagementWorkerInterface: '@FormBuilderBundle\OutputWorkflow\SuccessManagementWorker'
    FormBuilderBundle\OutputWorkflow\SuccessManagementWorker: ~

    FormBuilderBundle\OutputWorkflow\FormSubmissionFinisherInterface: '@FormBuilderBundle\OutputWorkflow\FormSubmissionFinisher'
    FormBuilderBundle\OutputWorkflow\FormSubmissionFinisher: ~

    FormBuilderBundle\OutputWorkflow\OutputWorkflowDispatcherInterface: '@FormBuilderBundle\OutputWorkflow\OutputWorkflowDispatcher'
    FormBuilderBundle\OutputWorkflow\OutputWorkflowDispatcher: ~

    FormBuilderBundle\OutputWorkflow\OutputWorkflowResolverInterface: '@FormBuilderBundle\OutputWorkflow\OutputWorkflowResolver'
    FormBuilderBundle\OutputWorkflow\OutputWorkflowResolver: ~

    FormBuilderBundle\Registry\OutputWorkflowChannelRegistry: ~
    FormBuilderBundle\Registry\FieldTransformerRegistry: ~

    FormBuilderBundle\Registry\FunnelLayerRegistry: ~
    FormBuilderBundle\Registry\FunnelActionRegistry: ~


    #
    # Signal

    FormBuilderBundle\EventSubscriber\SignalSubscribeHandler: ~


    #
    # Funnel

    FormBuilderBundle\OutputWorkflow\FunnelWorkerInterface: '@FormBuilderBundle\OutputWorkflow\FunnelWorker'
    FormBuilderBundle\OutputWorkflow\FunnelWorker: ~

    FormBuilderBundle\Resolver\FunnelDataResolver: ~