services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    FormBuilderBundle\Controller\AjaxController:
        calls:
            - [setContainer, ['@service_container']]

    FormBuilderBundle\Controller\Admin\ExportController:
        calls:
            - [setContainer, ['@service_container']]

    FormBuilderBundle\Controller\Admin\MailEditorController:
        calls:
            - [setContainer, ['@service_container']]

    FormBuilderBundle\Controller\Admin\SettingsController:
        calls:
            - [setContainer, ['@service_container']]

