services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # manager: form definition
    FormBuilderBundle\Manager\FormDefinitionManager:
        public: true

    # manager: output workflow
    FormBuilderBundle\Manager\OutputWorkflowManager:
        public: true

    # manager: preset
    FormBuilderBundle\Manager\PresetManager: ~

    # manager: template (form themes, type templates)
    FormBuilderBundle\Manager\TemplateManager: ~