services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool installer
    FormBuilderBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('FormBuilderBundle')"

    # tool: file locator
    FormBuilderBundle\Tool\FileLocator: ~

    # tool: href locale mapper
    FormBuilderBundle\Tool\HrefLocaleMapper: ~

    # configuration
    FormBuilderBundle\Configuration\Configuration: ~

    # session: configurator
    FormBuilderBundle\Session\SessionConfigurator:
        tags:
            - { name: pimcore.session.configurator }

