services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool installer
    FormBuilderBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('FormBuilderBundle')"

    # tool: file locator
    FormBuilderBundle\Tool\FormDependencyLocator: ~

    # tool: locale data mapper
    FormBuilderBundle\Tool\LocaleDataMapper: ~

    # tool: import/export forms via yaml definition
    FormBuilderBundle\Tool\ImportExportProcessor: ~

    # tool: recaptcha processor
    FormBuilderBundle\Tool\ReCaptchaProcessorInterface: '@FormBuilderBundle\Tool\ReCaptchaProcessor'
    FormBuilderBundle\Tool\ReCaptchaProcessor: ~

    # configuration
    FormBuilderBundle\Configuration\Configuration: ~

    # session: configurator
    FormBuilderBundle\Session\SessionConfigurator:
        tags:
            - { name: pimcore.session.configurator }

    # session: flash bag manager
    FormBuilderBundle\Session\FlashBagManagerInterface: '@FormBuilderBundle\Session\FlashBagManager'
    FormBuilderBundle\Session\FlashBagManager:
        public: false
